### ISSUE TITLE
Cannot see shark parameters in portrait mode while creating a new world

### ISSUE THREAD

**Issue by a-ira** [aperifons/Wa-Tor#1]
The shark parameters are not visible in my device screen when creating a new world In portrait mode. The numbers are shown in horizontal mode...

**Comment by a-ira** [comment]
I think could be a screen size limitation. When setting the two last parameters to a 3 digit number it becomes possible to see part of the first digit...

**Comment by aperifons** [comment]
@a-ira, Could you please post your screen resolution and your Android version?

**Comment by hydroid7** [comment]
Same issue. With Android 4.4.2

Link to Screenshot
http://i.imgur.com/gNCiRER.png
http://i.imgur.com/e0t6QRy.png

**Comment by a-ira** [comment]
Android version: 5.1.1
Screen resolution: 720 x 1280

**Comment by aperifons** [comment]
Should be fixed in v1.2

**Comment by a-ira** [comment]
Thanks :)
